
    #--------------------------------------------------------------------------------------#
    #                                                                                      #
    #                               [ Специальные ссылки ]                                 #
    #                                                                                      #
    #--------------------------------------------------------------------------------------#
    #                                                                                      #
    #                     AT-ProxyConnector: <ссылка на скачивание>                        #
    #                           AT-ProxyCaptcha: <в разработке>                            #
    #                                                                                      #
    #--------------------------------------------------------------------------------------#


# ==================================================================================================== #

# Настройка бинда проксей
#
# Здесь нужно указать IP адрес и порт, при вводе которых
# сервер будет пинговаться
#
# (ПОДДЕРЖКА МУЛЬТИ-ПРОКСИ)
proxies:
  Proxy-1: # Название прокси
    host: '127.0.0.1' # IP адрес сервера
    port: 25565 # Порт сервера

  Proxy-2: # Название прокси
    host: '127.0.0.1' # IP адрес сервера
    port: 25566 # Порт сервера

# Настройка визуализации сервера
#
# В данной настройке указывается название сервера (MOTD), а
# также максимально количество игроков
server:
  max-players: 150 # Максимальное количество игроков
  motd: # Название сервера
    - '   &6&lAdvanceTeam &8&l&k|&f AT-Proxy уже в сети! &8&l&k|&b vk.com/advanceteam_mc'
    - '                  &eItzStonlex & GitCoder'

# Настройка и создание серверов, которые будут
# стандартно подключаться к сети Proxy без коннектора
default_server: 'hub-1'
servers:
  hub-1: '127.0.0.1:25567'
  login-1: '127.0.0.1:25568'

# Настройки работы Proxy
settings:
  log_write_packet: false # Логирование отправки пакета клиенту
  log_read_packet: false # Логирование чтение пакета от сервера
  log_handle_packet: false # Логирование обработки пакетов
  log_command_dispatch: true # Логирование выполнения команды
  proxy_full_kick: true # Кикать игрока с сервера при заполненном сервере
  online_mode: false # Разрешение на заход только лицензионных игроков

# ==================================================================================================== #

  #--------------------------------------------#
  #              Авторы ядра:                  #
  #    ItzStonlex: https://vk.com/itzstonlex   #
  #    GitCoder: https://vk.com/james_the      #
  #--------------------------------------------#

# ==================================================================================================== #